Add option to specify a specific version by commit hash

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,6 +9,9 @@ inputs:
     description: Noir version to install. Defaults to the latest stable version.
     default: stable
     required: false
+  commit:
+    description: Noir version to install by commit
+    required: false
 
 runs:
   using: composite
@@ -22,12 +25,17 @@ runs:
       id: parse
       run: |
         : parse toolchain version
-        if [[ $toolchain == "stable" ]]; then
+        if [[ -n "$commit" ]]; then
+          if [[ "$toolchain" != "stable" ]]; then
+            echo "::error::Cannot specify both toolchain version and commit hash" && exit 1
+          fi
+          echo "toolchain=--commit $commit" >> $GITHUB_OUTPUT
+        elif [[ $toolchain == "stable" ]]; then
           : By default, noirup installs the latest stable version
         elif [[ $toolchain == "nightly" ]]; then
-          echo "toolchain="--nightly"" >> $GITHUB_OUTPUT
+          echo "toolchain=--nightly" >> $GITHUB_OUTPUT
         else
-          echo "toolchain="--version $toolchain"" >> $GITHUB_OUTPUT
+          echo "toolchain=--version $toolchain" >> $GITHUB_OUTPUT
         fi
       env:
         toolchain: ${{inputs.toolchain}}
@@ -47,6 +55,4 @@ runs:
 
     - name: Run Noirup
       shell: bash
-      run:
-        ${{ github.action_path }}/noirup ${{steps.parse.outputs.toolchain}} 
-      
+      run: ${{ github.action_path }}/noirup ${{steps.parse.outputs.toolchain}}
